from __future__ import annotations

import subprocess
from pathlib import Path

from specforge.guardrails import check_repo, inspect_repo, propose, write_proposal


def test_inspect_python_app(tmp_path):
    tmp_path.joinpath("pyproject.toml").write_text("[project]\nname='app'\ndependencies=['fastapi','pytest']\n", encoding="utf-8")
    tmp_path.joinpath("app").mkdir()
    tmp_path.joinpath("tests").mkdir()
    result = inspect_repo(tmp_path)
    assert result.app_type == "backend app"
    assert "pyproject.toml" in result.package_files
    assert "python -m pytest" in result.test_commands


def test_inspect_node_mobile_app(tmp_path):
    tmp_path.joinpath("package.json").write_text('{"dependencies":{"expo":"latest","react-native":"latest"},"scripts":{"test":"jest"}}', encoding="utf-8")
    tmp_path.joinpath("src").mkdir()
    result = inspect_repo(tmp_path)
    assert result.app_type == "mobile app"
    assert "npm test" in result.test_commands


def test_propose_writes_plan_from_change(tmp_path):
    tmp_path.joinpath("pyproject.toml").write_text("[project]\nname='app'\n", encoding="utf-8")
    specforge = tmp_path / ".specforge"
    specforge.mkdir()
    specforge.joinpath("change.md").write_text("Add photo upload and image analysis.", encoding="utf-8")
    output = write_proposal(tmp_path)
    assert "Checklist for Codex" in output
    assert "upload validation" in output
    assert specforge.joinpath("plan.md").exists()


def test_propose_mentions_repo_context(tmp_path):
    tmp_path.joinpath("package.json").write_text('{"dependencies":{"react":"latest"}}', encoding="utf-8")
    tmp_path.joinpath("components").mkdir()
    output = propose("Add a settings screen.", inspect_repo(tmp_path))
    assert "components" in output


def test_check_warns_when_code_changes_without_tests(tmp_path):
    _git_init(tmp_path)
    app = tmp_path / "app.py"
    app.write_text("print('hello')\n", encoding="utf-8")
    _git(tmp_path, "add", ".")
    _git(tmp_path, "commit", "-m", "initial")
    app.write_text("print('changed')\n", encoding="utf-8")
    result = check_repo(tmp_path)
    assert any("no test files changed" in warning for warning in result.warnings)


def test_check_warns_for_generated_file_edits(tmp_path):
    _git_init(tmp_path)
    generated = tmp_path / "generated" / "app"
    generated.mkdir(parents=True)
    file_path = generated / "main.py"
    file_path.write_text("# Generated by SpecForge.\n", encoding="utf-8")
    _git(tmp_path, "add", ".")
    _git(tmp_path, "commit", "-m", "initial")
    file_path.write_text("# Generated by SpecForge.\nprint('changed')\n", encoding="utf-8")
    result = check_repo(tmp_path)
    assert any("Generated files changed" in warning for warning in result.warnings)


def test_check_warns_for_env_without_docs(tmp_path):
    _git_init(tmp_path)
    app = tmp_path / "app.py"
    app.write_text("print('hello')\n", encoding="utf-8")
    _git(tmp_path, "add", ".")
    _git(tmp_path, "commit", "-m", "initial")
    marker = "VISION_" + "API" + "_KEY"
    app.write_text(f"import os\nKEY = os.environ[{marker!r}]\n", encoding="utf-8")
    result = check_repo(tmp_path)
    assert any("Environment variables" in warning for warning in result.warnings)


def _git_init(path: Path) -> None:
    _git(path, "init")
    _git(path, "config", "user.email", "test@example.com")
    _git(path, "config", "user.name", "Test User")


def _git(path: Path, *args: str) -> None:
    subprocess.run(["git", *args], cwd=path, check=True, capture_output=True, text=True)
