from __future__ import annotations

import re

from ...ast import AppSpec, Field, Model

HEADER = """# Generated by SpecForge.
# Source: .specforge/app.appspec
# Do not edit this file directly unless you intentionally detach it from SpecForge.

"""


def render_files(spec: AppSpec) -> dict[str, str]:
    return {
        "README.md": _readme(spec),
        "pyproject.toml": _pyproject(spec),
        "app/__init__.py": HEADER,
        "app/main.py": HEADER + _main(spec),
        "app/database.py": HEADER + _database(spec),
        "app/models.py": HEADER + _models(spec),
        "app/schemas.py": HEADER + _schemas(spec),
        "app/crud.py": HEADER + _crud(spec),
        "app/routes.py": HEADER + _routes(spec),
        "app/workflows.py": HEADER + _workflows(spec),
        "app/custom/__init__.py": "",
        "app/custom/hooks.py": _custom_hooks(),
        "tests/test_app.py": _test_app(spec),
        "tests/test_crud.py": _test_crud(spec),
        "tests/test_workflows.py": _test_workflows(spec),
    }


def _readme(spec: AppSpec) -> str:
    return f"""# {spec.app_name or "Generated App"}

Generated by SpecForge from `.specforge/app.appspec`.

## Run

```bash
pip install -e .
uvicorn app.main:app --reload
```

## Test

```bash
python -m pytest
```

Workflow functions in `app/workflows.py` are stubs in v0. Put user-owned code in `app/custom/`.
"""


def _pyproject(spec: AppSpec) -> str:
    name = _kebab(spec.app_name or "specforge-generated")
    return f"""[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "{name}"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "fastapi>=0.100",
  "pydantic>=2",
  "uvicorn>=0.23",
]

[project.optional-dependencies]
dev = ["pytest>=8", "httpx>=0.24"]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
"""


def _main(spec: AppSpec) -> str:
    return f"""from fastapi import FastAPI

from .database import init_db
from .routes import router

app = FastAPI(title={spec.app_name!r})


@app.on_event("startup")
def startup() -> None:
    init_db()


@app.get("/health")
def health() -> dict[str, str]:
    return {{"status": "ok"}}


app.include_router(router)
"""


def _database(spec: AppSpec) -> str:
    statements = []
    for model in sorted(spec.models, key=lambda m: m.name):
        cols = ['"id INTEGER PRIMARY KEY AUTOINCREMENT"']
        for field in sorted(model.fields, key=lambda f: f.name):
            nullable = "" if field.required else " NULL"
            cols.append(f'"{field.name} {_sqlite_type(field)}{nullable}"')
        joined = ", ".join(cols)
        statements.append(f'        "CREATE TABLE IF NOT EXISTS {_table(model)} ({joined})"')
    stmts = ",\n".join(statements) if statements else ""
    return f"""import sqlite3
from pathlib import Path

DB_PATH = Path(__file__).with_name("specforge.sqlite3")


def connect() -> sqlite3.Connection:
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def init_db() -> None:
    statements = [
{stmts}
    ]
    with connect() as conn:
        for statement in statements:
            conn.execute(statement)
        conn.commit()
"""


def _models(spec: AppSpec) -> str:
    payload = {
        model.name: [{"name": field.name, "type": field.type, "required": field.required} for field in sorted(model.fields, key=lambda f: f.name)]
        for model in sorted(spec.models, key=lambda m: m.name)
    }
    return f"""MODEL_FIELDS = {payload!r}
"""


def _schemas(spec: AppSpec) -> str:
    lines = ["from pydantic import BaseModel\n"]
    for model in sorted(spec.models, key=lambda m: m.name):
        lines.append(f"\nclass {model.name}Create(BaseModel):")
        _append_schema_fields(lines, model, create=True)
        lines.append(f"\n\nclass {model.name}Read({model.name}Create):")
        lines.append("    id: int")
    return "\n".join(lines) + "\n"


def _append_schema_fields(lines: list[str], model: Model, create: bool) -> None:
    if not model.fields:
        lines.append("    pass")
        return
    for field in sorted(model.fields, key=lambda f: f.name):
        typ = _py_type(field)
        if field.required:
            lines.append(f"    {field.name}: {typ}")
        else:
            lines.append(f"    {field.name}: {typ} | None = None")


def _crud(spec: AppSpec) -> str:
    lines = ["from .database import connect, init_db\n"]
    for model in sorted(spec.models, key=lambda m: m.name):
        names = [f.name for f in sorted(model.fields, key=lambda f: f.name)]
        table = _table(model)
        snake = _snake(model.name)
        lines.extend([
            f"\ndef create_{snake}(data: dict) -> dict:",
            "    init_db()",
        ])
        if names:
            cols = ", ".join(names)
            placeholders = ", ".join("?" for _ in names)
            values = ", ".join(f"data.get({name!r})" for name in names)
            lines.extend([
                "    with connect() as conn:",
                f"        cursor = conn.execute(\"INSERT INTO {table} ({cols}) VALUES ({placeholders})\", [{values}])",
                "        conn.commit()",
                f"        return get_{snake}(cursor.lastrowid)",
            ])
        else:
            lines.extend([
                "    with connect() as conn:",
                f"        cursor = conn.execute(\"INSERT INTO {table} DEFAULT VALUES\")",
                "        conn.commit()",
                f"        return get_{snake}(cursor.lastrowid)",
            ])
        lines.extend([
            f"\ndef list_{snake}s() -> list[dict]:",
            "    init_db()",
            "    with connect() as conn:",
            f"        return [dict(row) for row in conn.execute(\"SELECT * FROM {table} ORDER BY id\").fetchall()]",
            f"\ndef get_{snake}(item_id: int) -> dict:",
            "    init_db()",
            "    with connect() as conn:",
            f"        row = conn.execute(\"SELECT * FROM {table} WHERE id = ?\", [item_id]).fetchone()",
            "    if row is None:",
            "        raise KeyError(item_id)",
            "    return dict(row)",
            f"\ndef update_{snake}(item_id: int, data: dict) -> dict:",
            "    init_db()",
            f"    fields = {[name for name in names]!r}",
            "    updates = [name for name in fields if name in data]",
            "    if updates:",
            "        assignments = \", \".join(f\"{name} = ?\" for name in updates)",
            "        values = [data[name] for name in updates] + [item_id]",
            "        with connect() as conn:",
            f"            conn.execute(f\"UPDATE {table} SET {{assignments}} WHERE id = ?\", values)",
            "            conn.commit()",
            f"    return get_{snake}(item_id)",
            f"\ndef delete_{snake}(item_id: int) -> None:",
            "    init_db()",
            "    with connect() as conn:",
            f"        conn.execute(\"DELETE FROM {table} WHERE id = ?\", [item_id])",
            "        conn.commit()",
        ])
    return "\n".join(lines) + "\n"


def _routes(spec: AppSpec) -> str:
    imports = ["from fastapi import APIRouter, HTTPException", "from . import crud, schemas\n", "router = APIRouter()\n"]
    lines = imports[:]
    for model in sorted(spec.models, key=lambda m: m.name):
        snake = _snake(model.name)
        path = _kebab(model.name) + "s"
        lines.extend([
            f"\n@router.post('/{path}', response_model=schemas.{model.name}Read)",
            f"def create_{snake}(payload: schemas.{model.name}Create):",
            f"    return crud.create_{snake}(payload.model_dump())",
            f"\n@router.get('/{path}', response_model=list[schemas.{model.name}Read])",
            f"def list_{snake}s():",
            f"    return crud.list_{snake}s()",
            f"\n@router.get('/{path}/{{item_id}}', response_model=schemas.{model.name}Read)",
            f"def get_{snake}(item_id: int):",
            "    try:",
            f"        return crud.get_{snake}(item_id)",
            "    except KeyError:",
            "        raise HTTPException(status_code=404, detail='not found')",
            f"\n@router.put('/{path}/{{item_id}}', response_model=schemas.{model.name}Read)",
            f"def update_{snake}(item_id: int, payload: schemas.{model.name}Create):",
            "    try:",
            f"        return crud.update_{snake}(item_id, payload.model_dump(exclude_unset=True))",
            "    except KeyError:",
            "        raise HTTPException(status_code=404, detail='not found')",
            f"\n@router.delete('/{path}/{{item_id}}')",
            f"def delete_{snake}(item_id: int):",
            f"    crud.delete_{snake}(item_id)",
            "    return {'deleted': True}",
        ])
    return "\n".join(lines) + "\n"


def _workflows(spec: AppSpec) -> str:
    lines = ["WORKFLOW_METADATA = {"]
    for workflow in sorted(spec.workflows, key=lambda w: w.name):
        body = [line.text.strip() for line in workflow.lines]
        lines.append(f"    {workflow.name!r}: {body!r},")
    lines.append("}\n")
    for workflow in sorted(spec.workflows, key=lambda w: w.name):
        fn = _snake(workflow.name)
        lines.append(f"\ndef {fn}(payload: dict | None = None) -> dict:")
        lines.append(f"    \"\"\"Stub for workflow {workflow.name}.\"\"\"")
        for line in workflow.lines:
            lines.append(f"    # {line.text.strip()}")
        lines.append(f"    return {{'workflow': {workflow.name!r}, 'status': 'stub', 'payload': payload or {{}}}}")
    return "\n".join(lines) + "\n"


def _custom_hooks() -> str:
    return """# User-owned extension hooks.
# This file is not overwritten by spec intent in v0.


def before_workflow(name: str, payload: dict) -> dict:
    return payload
"""


def _test_app(spec: AppSpec) -> str:
    return """import pytest

fastapi = pytest.importorskip("fastapi")
from fastapi.testclient import TestClient

from app.main import app


def test_health():
    client = TestClient(app)
    response = client.get("/health")
    assert response.status_code == 200
    assert response.json()["status"] == "ok"
"""


def _test_crud(spec: AppSpec) -> str:
    if not spec.models:
        return "def test_no_models():\n    assert True\n"
    model = sorted(spec.models, key=lambda m: m.name)[0]
    payload = {field.name: _sample_value(field) for field in model.fields}
    path = "/" + _kebab(model.name) + "s"
    return f"""import pytest

fastapi = pytest.importorskip("fastapi")
from fastapi.testclient import TestClient

from app.main import app


def test_create_and_list_{_snake(model.name)}():
    client = TestClient(app)
    created = client.post({path!r}, json={payload!r})
    assert created.status_code == 200
    assert created.json()["id"] >= 1
    listed = client.get({path!r})
    assert listed.status_code == 200
    assert len(listed.json()) >= 1
"""


def _test_workflows(spec: AppSpec) -> str:
    lines = ["from app import workflows\n"]
    for workflow in sorted(spec.workflows, key=lambda w: w.name):
        fn = _snake(workflow.name)
        lines.extend([
            f"\ndef test_{fn}_stub():",
            f"    result = workflows.{fn}({{'example': True}})",
            f"    assert result['workflow'] == {workflow.name!r}",
            "    assert result['status'] == 'stub'",
        ])
    if len(lines) == 1:
        lines.append("\ndef test_no_workflows():\n    assert True")
    return "\n".join(lines) + "\n"


def _sqlite_type(field: Field) -> str:
    if field.type in {"number", "money"}:
        return "REAL"
    if field.type == "boolean":
        return "INTEGER"
    return "TEXT"


def _py_type(field: Field) -> str:
    if field.type in {"number", "money"}:
        return "float"
    if field.type == "boolean":
        return "bool"
    return "str"


def _sample_value(field: Field) -> object:
    if field.type in {"number", "money"}:
        return 10
    if field.type == "boolean":
        return True
    if field.type == "enum" and field.enum_values:
        return field.enum_values[0]
    return "example"


def _snake(name: str) -> str:
    value = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
    value = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", value)
    return re.sub(r"[^a-zA-Z0-9_]+", "_", value).lower().strip("_")


def _kebab(name: str) -> str:
    return _snake(name).replace("_", "-")


def _table(model: Model) -> str:
    return _snake(model.name)
