from __future__ import annotations

from pathlib import Path

TERMS = [
    "chat" + "gpt",
    "generated by " + "ai",
    "created by " + "ai",
    "codex " + "prompt",
    "claude " + "prompt",
    "api" + "_key",
    "sec" + "ret",
    "to" + "ken",
    "pass" + "word",
    "c:" + "\\users",
    "d:" + "\\",
    "jmp" + "anal",
    "juan" + "ma",
]

IGNORED_DIRS = {".git", ".venv", "venv", "__pycache__", ".pytest_cache", ".mypy_cache", ".ruff_cache", "dist", "build", "htmlcov", ".specforge/cache"}
IGNORED_SUFFIXES = {".pyc", ".png", ".jpg", ".jpeg", ".gif", ".ico", ".sqlite3"}
ALLOWED_PUBLIC_TEXT = {".gitignore", "docs/benchmarks.md", "docs/security.md", "specforge/privacy.py", "tests/test_privacy.py"}
ALLOWED_PUBLIC_LINES = {"pip install git+https://github.com/jmpanal/specforge"}


def scan(root: str | Path = ".") -> list[tuple[Path, int, str]]:
    root_path = Path(root)
    matches: list[tuple[Path, int, str]] = []
    for path in sorted(root_path.rglob("*")):
        rel = path.relative_to(root_path)
        if _ignored(rel, path):
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        haystack_lines = text.splitlines()
        for line_no, line in enumerate(haystack_lines, start=1):
            lowered = line.lower()
            if lowered.strip() in ALLOWED_PUBLIC_LINES:
                continue
            if any(_matches(term, lowered) for term in TERMS):
                matches.append((rel, line_no, line.strip()))
    return matches


def _matches(term: str, lowered_line: str) -> bool:
    if term == "d:" + "\\":
        return term in lowered_line and "d:" + "\\n" not in lowered_line
    return term in lowered_line


def _ignored(rel: Path, path: Path) -> bool:
    if not path.is_file():
        return True
    if path.suffix.lower() in IGNORED_SUFFIXES:
        return True
    if rel.as_posix() in ALLOWED_PUBLIC_TEXT:
        return True
    parts = set(rel.parts)
    return bool(parts & IGNORED_DIRS)
